# Generated by Django 2.2.2 on 2020-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
