# Generated by Django 2.2.2 on 2020-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_auto_20200605_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
