# Generated by Django 2.2.2 on 2020-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_add_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add_job',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
