# Generated by Django 2.2.2 on 2020-06-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_add_job_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.Add_job')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.SignupUser')),
            ],
        ),
    ]
